version: '3.7'

services:
  postgresdb:
    image: postgres:14
    container_name: postgresdb
    environment:
      POSTGRES_PASSWORD: changeme
      POSTGRES_DB: mydb
    ports:
      - 5432:5432
    networks:
      - postgresNet

  pgadmin:
    container_name: mypgadmin
    image: dpage/pgadmin4:7.2
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 8001:80
    networks:
      - postgresNet
    depends_on:
      - postgresdb

  phinx:
    image: phinx:1.0-beta
    container_name: phinx
    volumes:
      - $PWD/db:/phinx/db
    environment:
      PHINX_DB_ADAPTER: pgsql
      PHINX_DB_HOST: postgresdb
      PHINX_DB_DATABASE: mydb
      PHINX_DB_USERNAME: postgres
      PHINX_DB_PASSWORD: changeme
      PHINX_DB_PORT: 5432
    networks:
      - postgresNet
    depends_on:
      - postgresdb

networks:
  postgresNet: