version: '3.7'

services:
  phinx:
    image: uzrnem/phinx:0.4
    container_name: phinx
    volumes:
      - $PWD/db:/phinx/db
    environment:
      PHINX_DB_ADAPTER: mysql
      PHINX_DB_HOST: mysqlhost
      PHINX_DB_DATABASE: mydb
      PHINX_DB_USERNAME: root
      PHINX_DB_PASSWORD: root
      PHINX_DB_PORT: 3306
    command: tail -f /dev/null
    networks:
      - docker-compose-files_mysql

networks:
  docker-compose-files_mysql:
    external: true